//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 5/22/2016 9:34:47 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.StructureType in the schema.
    /// </summary>
    public enum StructureType : int
    {
    
        /// <summary>
        /// There are no comments for StructureType.CoverPage in the schema.
        /// </summary>
        CoverPage = 1,    
        /// <summary>
        /// There are no comments for StructureType.Reference in the schema.
        /// </summary>
        Reference = 2,    
        /// <summary>
        /// There are no comments for StructureType.Section in the schema.
        /// </summary>
        Section = 3,    
        /// <summary>
        /// There are no comments for StructureType.Subsection in the schema.
        /// </summary>
        Subsection = 4,    
        /// <summary>
        /// There are no comments for StructureType.Subsubsection in the schema.
        /// </summary>
        Subsubsection = 5
    }

}
