//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 5/29/2016 10:11:02 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.TaskState in the schema.
    /// </summary>
    public enum TaskState : int
    {
    
        /// <summary>
        /// There are no comments for TaskState.Locked in the schema.
        /// </summary>
        Locked = 1,    
        /// <summary>
        /// There are no comments for TaskState.InProgress in the schema.
        /// </summary>
        InProgress = 3,    
        /// <summary>
        /// There are no comments for TaskState.Done in the schema.
        /// </summary>
        Done = 5,    
        /// <summary>
        /// There are no comments for TaskState.Resolved in the schema.
        /// </summary>
        Resolved = 6,    
        /// <summary>
        /// There are no comments for TaskState.Closed in the schema.
        /// </summary>
        Closed = 7,    
        /// <summary>
        /// There are no comments for TaskState.WontBeDone in the schema.
        /// </summary>
        WontBeDone = 8,    
        /// <summary>
        /// There are no comments for TaskState.ToDo in the schema.
        /// </summary>
        ToDo = 2,    
        /// <summary>
        /// There are no comments for TaskState.Expired in the schema.
        /// </summary>
        Expired = 4
    }

}
