//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 5/9/2016 10:51:07 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.NEWTABLE in the schema.
    /// </summary>
    /// <KeyProperties>
    /// IdnewTable
    /// </KeyProperties>
    [EdmEntityTypeAttribute(NamespaceName="MtcModel", Name="NEWTABLE")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class NEWTABLE : EntityObject    {
        #region Factory Method

        /// <summary>
        /// Create a new NEWTABLE object.
        /// </summary>
        /// <param name="idnewTable">Initial value of IdnewTable.</param>
        public static NEWTABLE CreateNEWTABLE(int idnewTable)
        {
            NEWTABLE nEWTABLE = new NEWTABLE();
            nEWTABLE.IdnewTable = idnewTable;
            return nEWTABLE;
        }

        #endregion

        #region Properties
    
        /// <summary>
        /// There are no comments for IdnewTable in the schema.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public int IdnewTable
        {
            get
            {
                int value = _IdnewTable;
                OnGetIdnewTable(ref value);
                return value;
            }
            set
            {
                if (_IdnewTable != value)
                {
                  OnIdnewTableChanging(ref value);
                  ReportPropertyChanging("IdnewTable");
                  _IdnewTable = StructuralObject.SetValidValue(value);
                  ReportPropertyChanged("IdnewTable");
                  OnIdnewTableChanged();
              }
            }
        }
        private int _IdnewTable;
        partial void OnGetIdnewTable(ref int value);
        partial void OnIdnewTableChanging(ref int value);
        partial void OnIdnewTableChanged();

        #endregion
    }

}
