//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 5/11/2016 11:55:44 AM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.ReferenceType in the schema.
    /// </summary>
    [EdmEnumTypeAttribute(NamespaceName="MtcModel", Name="ReferenceType")]
    [DataContract]
    public enum ReferenceType : int
    {
    
        /// <summary>
        /// There are no comments for ReferenceType.Book in the schema.
        /// </summary>
        [EnumMember]
        Book = 1,    
        /// <summary>
        /// There are no comments for ReferenceType.Article in the schema.
        /// </summary>
        [EnumMember]
        Article = 2,    
        /// <summary>
        /// There are no comments for ReferenceType.Web in the schema.
        /// </summary>
        [EnumMember]
        Web = 3
    }

}
