//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 5/9/2016 4:32:41 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.StructureType in the schema.
    /// </summary>
    [EdmEnumTypeAttribute(NamespaceName="MtcModel", Name="StructureType")]
    [DataContract]
    public enum StructureType : int
    {
    
        /// <summary>
        /// There are no comments for StructureType.CoverPage in the schema.
        /// </summary>
        [EnumMember]
        CoverPage = 1,    
        /// <summary>
        /// There are no comments for StructureType.Reference in the schema.
        /// </summary>
        [EnumMember]
        Reference = 2,    
        /// <summary>
        /// There are no comments for StructureType.Section in the schema.
        /// </summary>
        [EnumMember]
        Section = 3,    
        /// <summary>
        /// There are no comments for StructureType.Subsection in the schema.
        /// </summary>
        [EnumMember]
        Subsection = 4,    
        /// <summary>
        /// There are no comments for StructureType.Subsubsection in the schema.
        /// </summary>
        [EnumMember]
        Subsubsection = 5
    }

}
