-- Script was generated by Devart Entity Developer, Version 5.8.742.0
-- Script date 5/18/2016 7:50:43 AM
-- Target Server: MySQL
-- Server Version: 5.6

-- 
-- Creating a table mtc.documenttemplate 
-- 
CREATE TABLE mtc.documenttemplate (
   Id INT NOT NULL AUTO_INCREMENT,
   Name VARCHAR(45) NULL,
   Description VARCHAR(100) NULL,
   IsActive TINYINT UNSIGNED NOT NULL,
   PRIMARY KEY (Id)
);

-- 
-- Creating a table mtc.structureelement 
-- 
CREATE TABLE mtc.structureelement (
   Id INT NOT NULL AUTO_INCREMENT,
   Title VARCHAR(255) NULL,
   StructureTypeId INT NOT NULL,
   Description VARCHAR(455) NULL,
   `Order` INT NULL,
   PRIMARY KEY (Id)
);

-- 
-- Creating a table mtc.user 
-- 
CREATE TABLE mtc.user (
   Id INT NOT NULL AUTO_INCREMENT,
   FirstName VARCHAR(45) NOT NULL,
   MiddleName VARCHAR(45) NULL,
   FamilyName VARCHAR(45) NOT NULL,
   UserName VARCHAR(45) NOT NULL,
   Email VARCHAR(45) NOT NULL,
   `Password` VARCHAR(45) NOT NULL,
   ExperiencePoints INT NULL,
   Level SMALLINT NULL,
   PRIMARY KEY (Id)
);

-- 
-- Creating a table mtc.structurerelation 
-- 
CREATE TABLE mtc.structurerelation (
   StructureElementParentId INT NOT NULL,
   StructureElementChildId INT NOT NULL,
   PRIMARY KEY (StructureElementParentId, StructureElementChildId),
   CONSTRAINT FK_StructureElement_Child FOREIGN KEY (StructureElementChildId) REFERENCES mtc.structureelement (Id),
   CONSTRAINT FK_StructureElement_Parent FOREIGN KEY (StructureElementParentId) REFERENCES mtc.structureelement (Id)
);

-- 
-- Creating a table mtc.document 
-- 
CREATE TABLE mtc.document (
   ID INT NOT NULL AUTO_INCREMENT,
   UserId INT NOT NULL,
   Deadline DATETIME NOT NULL,
   Title VARCHAR(100) NOT NULL,
   CurrentProgress INT NULL,
   MentorId INT NULL,
   DocumentTemplateId INT NOT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_DocumentDocumentTemplate_ID FOREIGN KEY (DocumentTemplateId) REFERENCES mtc.documenttemplate (Id),
   CONSTRAINT FK_DocumentMentor_ID FOREIGN KEY (MentorId) REFERENCES mtc.user (Id),
   CONSTRAINT FK_DocumentUser_ID FOREIGN KEY (UserId) REFERENCES mtc.user (Id)
);

-- 
-- Creating a table mtc.documentstructurerelation 
-- 
CREATE TABLE mtc.documentstructurerelation (
   DocumentTemplateId INT NOT NULL,
   StructureElementId INT NOT NULL,
   PRIMARY KEY (DocumentTemplateId, StructureElementId),
   CONSTRAINT FK_DocumentTemplate_ID FOREIGN KEY (DocumentTemplateId) REFERENCES mtc.documenttemplate (Id),
   CONSTRAINT FK_StructureElement_ID FOREIGN KEY (StructureElementId) REFERENCES mtc.structureelement (Id)
);

-- 
-- Creating a table mtc.reference 
-- 
CREATE TABLE mtc.reference (
   Id INT NOT NULL AUTO_INCREMENT,
   ReferenceTypeId INT NULL,
   Name VARCHAR(45) NULL,
   `Order` INT NULL,
   DocumentId INT NOT NULL,
   PRIMARY KEY (Id),
   CONSTRAINT FK_ReferenceDocument_Id FOREIGN KEY (DocumentId) REFERENCES mtc.document (ID)
);

-- 
-- Creating a table mtc.structurecontent 
-- 
CREATE TABLE mtc.structurecontent (
   Id INT NOT NULL AUTO_INCREMENT,
   StructureElementId INT NOT NULL,
   Title VARCHAR(45) NULL,
   Content LONGBLOB NULL,
   DocumentId INT NOT NULL,
   `Order` INT NOT NULL,
   CurrentProgress INT NULL,
   PRIMARY KEY (Id),
   CONSTRAINT FK_StructureContentDocument_Id FOREIGN KEY (DocumentId) REFERENCES mtc.document (ID),
   CONSTRAINT FK_StructureElementDocument_Id FOREIGN KEY (StructureElementId) REFERENCES mtc.structureelement (Id)
);

-- 
-- Creating a table mtc.task 
-- 
CREATE TABLE mtc.task (
   Id INT NOT NULL AUTO_INCREMENT,
   Title VARCHAR(45) NOT NULL,
   AssignTo INT NULL,
   TaskState INT NOT NULL,
   Deadline DATETIME NOT NULL,
   DocumentId INT NOT NULL,
   `Order` INT NULL,
   TaskType INT NOT NULL,
   IsLocked TINYINT UNSIGNED NOT NULL,
   StrucktureContentId INT NULL,
   PRIMARY KEY (Id),
   CONSTRAINT FK_TaskDocument_Id FOREIGN KEY (DocumentId) REFERENCES mtc.document (ID),
   CONSTRAINT FK_TaskStructureContent_Id FOREIGN KEY (StrucktureContentId) REFERENCES mtc.structurecontent (Id),
   CONSTRAINT FK_TaskUser_Id FOREIGN KEY (AssignTo) REFERENCES mtc.user (Id)
);

