//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 7/2/2016 4:43:03 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.ExportDocumentType in the schema.
    /// </summary>
    public enum ExportDocumentType : int
    {
    
        /// <summary>
        /// There are no comments for ExportDocumentType.Docx in the schema.
        /// </summary>
        Docx = 1,    
        /// <summary>
        /// There are no comments for ExportDocumentType.Txt in the schema.
        /// </summary>
        Txt = 2,    
        /// <summary>
        /// There are no comments for ExportDocumentType.Pdf in the schema.
        /// </summary>
        Pdf = 3,    
        /// <summary>
        /// There are no comments for ExportDocumentType.Csv in the schema.
        /// </summary>
        Csv = 4
    }

}
