//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 6/22/2016 10:49:36 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.DocumentState in the schema.
    /// </summary>
    public enum DocumentState : int
    {
    
        /// <summary>
        /// There are no comments for DocumentState.Started in the schema.
        /// </summary>
        Started = 1,    
        /// <summary>
        /// There are no comments for DocumentState.InProgress in the schema.
        /// </summary>
        InProgress = 2,    
        /// <summary>
        /// There are no comments for DocumentState.Finished in the schema.
        /// </summary>
        Finished = 3,    
        /// <summary>
        /// There are no comments for DocumentState.Rejected in the schema.
        /// </summary>
        Rejected = 4
    }

}
