//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework DbContext template.
// Code is generated on: 7/10/2016 5:17:43 PM
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.Specialized;

namespace MtcModel
{

    /// <summary>
    /// There are no comments for MtcModel.TaskAction in the schema.
    /// </summary>
    public enum TaskAction : int
    {
    
        /// <summary>
        /// There are no comments for TaskAction.Start in the schema.
        /// </summary>
        Start = 1,    
        /// <summary>
        /// There are no comments for TaskAction.Finish in the schema.
        /// </summary>
        Finish = 2,    
        /// <summary>
        /// There are no comments for TaskAction.Reject in the schema.
        /// </summary>
        Reject = 3,    
        /// <summary>
        /// There are no comments for TaskAction.Nothing in the schema.
        /// </summary>
        Nothing = 4,    
        /// <summary>
        /// There are no comments for TaskAction.Locked in the schema.
        /// </summary>
        Locked = 5
    }

}
